### ISSUE TITLE
Create CLI tool for projectman

### ISSUE THREAD

**Issue by thepetk** [thepetk/projectman#33]
/type feature

## Which area this feature is related to?

/label ci
/label json-configuration
/label github-provider

## Which functionality do you think we should add?

This EPIC is focusing on a new scope for the project. Right now the `projectman` application is meant to be available only as a `github-action`. As a developer I'd might prefer to use it as a CLI tool, run it through my own self-hosted cronjobs or manually from my terminal.

## Describe the solution you'd like

The main functionality of the project should remain the same, although we will have to separate the usage information. We should provide information on how to build/install the cli locally and what commands you can run.

Other than that, we should create new functionality using a cli tool (like click) and a setup process in order to make it available to all users. Of course we will have to define which will be the commands and the flags supported by the cli tool. 

## Additional context

A good way to start is to explore options through click: https://click.palletsprojects.com/en/8.1.x/

## Acceptance Criteria

- [ ] Investigate Click as base for the Projectman CLI.
- [ ] Investigate Commands & Flags used by the Projectman CLI.
- [ ] Implement the CLI commands and flags.
- [ ] Update usage & setup instructions with the Projectman CLI info.
